export const TOGGLE_LOADER = 'TOGGLE_LOADER';
export const TOGGLE_MAIN_LOADER = 'TOGGLE_MAIN_LOADER';
export const SET_PACKAGES = 'SET_PACKAGES';
export const SET_ACTIVE = 'SET_ACTIVE';
export const SET_APP_MESSAGE = 'SET_APP_MESSAGE';
