//toggles
export const TOGGLE_LOADER = "TOGGLE_LOADER";
export const TOGGLE_MAIN_LOADER = "TOGGLE_MAIN_LOADER";
export const TOGGLE_MODAL = "TOGGLE_MODAL";

//setters
export const SET_PACKAGES = "SET_PACKAGES";
export const SET_PACKAGES_OUTDATED = "SET_PACKAGES_OUTDATED";
export const SET_PACKAGE_ACTIONS = "SET_PACKAGE_ACTIONS";
export const SET_PACKAGE_JSON = "SET_PACKAGE_JSON";
export const SET_ACTIVE = "SET_ACTIVE";
export const SET_MODE = "SET_MODE";
export const SET_ACTIVE_SIDEBAR = "SET_ACTIVE_SIDEBAR";

//various
export const TOTAL_INSTALLED = "TOTAL_INSTALLED";
export const DO_INSTALL = "DO_INSTALL";
export const ADD_MESSAGE = "ADD_MESSAGE";
export const CLEAR_MESSAGES = "CLEAR_MESSAGES";
export const ADD_COMMAND_OPTION = "ADD_COMMAND_OPTION";
export const CLEAR_COMMAND_OPTIONS = "CLEAR_COMMAND_OPTIONS";
