// UI
export const TOGGLE_LOADER = '@@UI/TOGGLE_LOADER';
export const TOGGLE_MAIN_LOADER = '@@UI/TOGGLE_MAIN_LOADER';
export const TOGGLE_SETTINGS = '@@UI/TOGGLE_SETTINGS';
export const TOGGLE_EXPANDED = '@@UI/TOGGLE_EXPANDED';
export const TOGGLE_SNACKBAR = '@@UI/TOGGLE_SNACKBAR';
export const TOGGLE_DRAWER = '@@UI/TOGGLE_DRAWER';
export const TOGGLE_FILTERS = '@@UI/TOGGLE_FILTERS';
export const TOGGLE_DETAILS = '@@UI/TOGGLE_DETAILS';
export const MENU_OPEN = '@@UI/MENU_OPEN';
export const SET_ACTIVE_SIDEBAR = '@@UI/SET_ACTIVE_SIDEBAR';

// DATA
export const SET_OPENED_PACKAGES = '@@DATA/SET_OPENED_PACKAGES';
export const SET_SELECTED_PACKAGE = '@@DATA/SET_SELECTED_PACKAGE';
export const SET_PAGE = '@@DATASET_PAGE';
export const SET_ROWS_PER_PAGE = '@@DATASET_ROWS_PER_PAGE';
export const SET_VERSION = '@@DATASET_VERSION';
export const SET_TAB_INDEX = '@@DATASET_TAB_INDEX';
export const SET_SETTINGS = '@@DATASET_SETTINGS';
export const SET_PACKAGES = '@@DATASET_PACKAGES';
export const SET_PACKAGES_OUTDATED = '@@DATASET_PACKAGES_OUTDATED';
export const SET_PACKAGE_ACTIONS = '@@DATASET_PACKAGE_ACTIONS';
export const SET_PACKAGE_JSON = '@@DATASET_PACKAGE_JSON';
export const SET_PACKAGE_GROUP = '@@DATASET_PACKAGE_GROUP';
export const SET_ACTIVE = '@@DATASET_ACTIVE';
export const SET_MODE = '@@DATASET_MODE';
export const SET_MANAGER = '@@DATASET_MANAGER';
export const SET_TOTAL = '@@DATA/SET_TOTAL';
export const SETUP_SNACKBAR = '@@DATA/SETUP_SNACKBAR';
export const SET_ERROR = '@@DATA/SET_ERROR';

// COMMON
export const DO_INSTALL = '@@ACTION/DO_INSTALL';
export const ADD_FILTER = '@@ACTION/ADD_FILTER';
export const CLEAR_FILTERS = '@@ACTION/CLEAR_FILTERS';
export const ADD_MESSAGE = '@@ACTION/ADD_MESSAGE';
export const CLEAR_MESSAGES = '@@ACTION/CLEAR_MESSAGES';
export const ADD_COMMAND_OPTION = '@@ACTION/ADD_COMMAND_OPTION';
export const REMOVE_COMMAND_OPTION = '@@ACTION/REMOVE_COMMAND_OPTION';
export const CLEAR_COMMAND_OPTIONS = '@@ACTION/CLEAR_COMMAND_OPTIONS';
export const CLEAR_SELECTED = '@@ACTION/CLEAR_SELECTED';
export const REMOVE_PACKAGES = '@@ACTION/REMOVE_PACKAGES';
